require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - bin/**/*

Rails:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

RSpec/ImplicitSubject:
  Enabled: false    

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - and
    - but
